package tests;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;

public class GeneratePDF {

    public static void main(String[] args) {
        String pdfPath = "cardio_ai_app_architecture.pdf";
        try {
            createPdf(pdfPath);
            System.out.println("PDF generated successfully: " + pdfPath);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void createPdf(String filename) throws IOException {
        StringBuilder stream = new StringBuilder();
        
        // Page 1 Header
        addText(stream, "/F2", 20, 40, 750, "CardioAI - Application Architecture & Tech Stack");
        addLine(stream, 40, 740, 570, 740, 2);
        
        addText(stream, "/F2", 13, 40, 715, "1. Executive Summary & Application Overview");
        addText(stream, "/F1", 10, 40, 698, "CardioAI (CardioProgress) is a dual-platform medical AI system designed for cardiac fibrosis");
        addText(stream, "/F1", 10, 40, 684, "risk assessment, biomarker tracking, and report diagnosis. It operates seamlessly across both");
        addText(stream, "/F1", 10, 40, 670, "Android Mobile Devices and Web Browsers connected to a shared cloud database.");

        addText(stream, "/F2", 13, 40, 640, "2. Frontend Technologies & Languages");
        
        addText(stream, "/F2", 11, 50, 622, "A. Android Mobile App (kotlinapp):");
        addText(stream, "/F1", 10, 60, 606, "• Programming Language: Kotlin (1.9+)");
        addText(stream, "/F1", 10, 60, 592, "• UI Framework: Jetpack Compose (Declarative Modern UI Framework)");
        addText(stream, "/F1", 10, 60, 578, "• Design Tokens & Components: Material 3, Custom Card Gradients, Canvas Gauges");
        addText(stream, "/F1", 10, 60, 564, "• Concurrency: Kotlin Coroutines & StateFlow (Dispatchers.IO, ViewModel lifecycle)");
        addText(stream, "/F1", 10, 60, 550, "• Local Persistence: SharedPreferences (AppSettings persistent session manager)");

        addText(stream, "/F2", 11, 50, 524, "B. Web Application (webapp):");
        addText(stream, "/F1", 10, 60, 508, "• Markup Language: HTML5 (Semantic Structure, Accessible Form Elements)");
        addText(stream, "/F1", 10, 60, 494, "• Styling & Aesthetics: Vanilla CSS3 (Glassmorphism, Dark/Light Themes, Flexbox/Grid)");
        addText(stream, "/F1", 10, 60, 480, "• Client Logic: JavaScript (ES6+ Modern Syntax, Asynchronous Promises, Event Engine)");
        addText(stream, "/F1", 10, 60, 466, "• Icons & Typography: FontAwesome 6 Pro, Google Inter/Outfit Fonts");
        addText(stream, "/F1", 10, 60, 452, "• Local Cache: HTML5 LocalStorage (Instant zero-latency UI rendering)");

        addText(stream, "/F2", 13, 40, 422, "3. Backend Technologies, Cloud DB & AI Engine");
        
        addText(stream, "/F2", 11, 50, 404, "A. Database & Cloud Architecture:");
        addText(stream, "/F1", 10, 60, 388, "• Database Engine: Firebase Firestore (NoSQL Document-based Cloud Database)");
        addText(stream, "/F1", 10, 60, 374, "• Collections Schema: 'users' (Profiles), 'patient_details' (Vitals/BMI), 'reports' (Scans)");
        addText(stream, "/F1", 10, 60, 360, "• User Authentication: Firebase Auth (Email/Password Auth, UID-based Security)");

        addText(stream, "/F2", 11, 50, 334, "B. Artificial Intelligence & Optical OCR Engine:");
        addText(stream, "/F1", 10, 60, 318, "• Document Reader: Google ML Kit Vision OCR (Text Recognition v2)");
        addText(stream, "/F1", 10, 60, 304, "• Generative AI: Google Gemini AI API (LLM Biomarker Summarization & Clinical Insights)");
        addText(stream, "/F1", 10, 60, 290, "• Heuristic Risk Classifier: Evaluates Troponin I, BNP, NT-proBNP & LVEF metrics");

        addText(stream, "/F2", 13, 40, 260, "4. Real-Time Data Synchronization Architecture");
        addText(stream, "/F1", 10, 40, 244, "• Android Listener: DisposableEffect binding addSnapshotListener on Firestore documents.");
        addText(stream, "/F1", 10, 40, 230, "• Web Listener: Firebase Web SDK onSnapshot observers attached to user & patient collections.");
        addText(stream, "/F1", 10, 40, 216, "• Multi-Device Sync: Any change made on Web updates Android live within 1 second and vice versa.");
        addText(stream, "/F1", 10, 40, 202, "• Data Normalization: Biomarker height_cm & weight_kg are stored consistently as Numbers.");

        addText(stream, "/F1", 9, 40, 60, "Generated by CardioAI System Architecture Suite | Project: cardio-ai-635a5");

        byte[] streamBytes = stream.toString().getBytes("ISO-8859-1");

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        out.write("%PDF-1.4\n".getBytes());

        long obj1 = out.size();
        out.write("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n".getBytes());

        long obj2 = out.size();
        out.write("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n".getBytes());

        long obj3 = out.size();
        out.write("3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /MediaBox [0 0 612 792] /Contents 6 0 R >>\nendobj\n".getBytes());

        long obj4 = out.size();
        out.write("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n".getBytes());

        long obj5 = out.size();
        out.write("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n".getBytes());

        long obj6 = out.size();
        out.write(("6 0 obj\n<< /Length " + streamBytes.length + " >>\nstream\n").getBytes());
        out.write(streamBytes);
        out.write("\nendstream\nendobj\n".getBytes());

        long xrefPos = out.size();
        out.write("xref\n0 7\n".getBytes());
        out.write("0000000000 65535 f \n".getBytes());
        out.write(String.format("%010d 00000 n \n", obj1).getBytes());
        out.write(String.format("%010d 00000 n \n", obj2).getBytes());
        out.write(String.format("%010d 00000 n \n", obj3).getBytes());
        out.write(String.format("%010d 00000 n \n", obj4).getBytes());
        out.write(String.format("%010d 00000 n \n", obj5).getBytes());
        out.write(String.format("%010d 00000 n \n", obj6).getBytes());

        out.write("trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n".getBytes());
        out.write(String.valueOf(xrefPos).getBytes());
        out.write("\n%%EOF\n".getBytes());

        try (FileOutputStream fos = new FileOutputStream(filename)) {
            out.writeTo(fos);
        }
    }

    private static void addText(StringBuilder sb, String font, int size, int x, int y, String text) {
        sb.append("BT ").append(font).append(" ").append(size).append(" Tf ").append(x).append(" ").append(y).append(" Td (").append(escapePdfText(text)).append(") Tj ET\n");
    }

    private static void addLine(StringBuilder sb, int x1, int y1, int x2, int y2, int width) {
        sb.append(width).append(" w ").append(x1).append(" ").append(y1).append(" m ").append(x2).append(" ").append(y2).append(" l S\n");
    }

    private static String escapePdfText(String text) {
        return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
    }
}
